### ISSUE TITLE
Implement Audit Logs page content

### ISSUE THREAD

**Issue by JulioCesarDias** [conveyordata/data-product-portal#22] opened 2024-06-28 13:42 UTC
## Summary
Implement content for the Audit Logs page which would include historical relevant change logs

### Motivation
Showing audit logs would allow users to have an overview of the relevant events on data products, datasets and users within the platform

**Comment by stijn-janssens** [comment] 2024-12-06 12:31
duplicate of #321

**Closed by stijn-janssens** 2024-12-06 12:31 UTC
Labels: enhancement
